FROM golang:1.20 as build

WORKDIR /app

COPY go.mod go.sum* ./
RUN if [ -f go.mod ]; then go mod download; fi

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server

FROM alpine:latest
EXPOSE 8099
COPY --from=build /server /server
CMD ["sh", "-c", "/server -listen=${LISTEN} -readTimeout=600 -writeTimeout=100"]