FROM golang:1.20 as build

WORKDIR /app

COPY go.mod go.sum* ./
RUN if [ -f go.mod ]; then go mod download; fi

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /client ./cmd/client

FROM alpine:latest
EXPOSE 8099
COPY --from=build /client /client
CMD ["/client"]